import { Providers } from '@/providers';
import { cn } from '@nextui-org/theme';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Storage',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700', '800'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(openSans.className)} suppressHydrationWarning>
      <body className="min-h-screen">
        <Providers>{children}</Providers>
        <ToastContainer position="bottom-right" hideProgressBar />
      </body>
    </html>
  );
}
